#!/bin/bash
# Code Signing 快速參考

echo "======================================"
echo "   XIVTheCalamity Code Signing"
echo "======================================"
echo ""
echo "🔧 開發測試（不簽名）"
echo "   ./scripts/build-and-test.sh"
echo ""
echo "🚀 生產發布（含簽名）"
echo "   ./scripts/quick-pack.sh"
echo ""
echo "─────────────────────────────────────"
echo ""
echo "📋 NPM 命令（進階用法）"
echo "   開發: cd frontend && npm run build:dev"
echo "   生產: cd frontend && npm run build:prod"
echo ""
echo "🔍 查看憑證"
echo "   security find-identity -v -p codesigning"
echo ""
echo "✅ 驗證簽名"
echo "   codesign --verify --deep --strict Release/mac-arm64/XIVTheCalamity.app"
echo ""
echo "======================================"
echo ""
echo "💡 提示："
echo "   - 測試開發：build-and-test.sh"
echo "   - 發布產品：quick-pack.sh"
echo "   - 不需要手動修改配置"
echo ""
